-- MySQL Script generated by MySQL Workbench
-- Mon Nov 28 16:10:14 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema rmq-community
-- -----------------------------------------------------
-- rocketmq 社区

-- -----------------------------------------------------
-- Schema rmq-community
--
-- rocketmq 社区
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `rmq-community` DEFAULT CHARACTER SET utf8 ;
USE `rmq-community` ;

-- -----------------------------------------------------
-- Table `rmq-community`.`banner`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmq-community`.`banner` (
  `id` INT NOT NULL ,
  `desc` CHAR(45) NULL,
  `image_url` FLOAT NULL COMMENT '图片描述',
  `title` VARCHAR(45) NULL COMMENT '标题',
  `status` VARCHAR(45) NULL COMMENT '使用状态',
  `updatetime` VARCHAR(45) NULL,
  `link_url` VARCHAR(45) NULL COMMENT '超链接地址',
  `bgColor` VARCHAR(45) NULL COMMENT '背景色',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmq-community`.`activities`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmq-community`.`activities` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(45) NULL COMMENT '活动背景图',
  `location` VARCHAR(45) NULL COMMENT '活动地址',
  `name` VARCHAR(45) NULL COMMENT '活动名称',
  `start` VARCHAR(45) NULL COMMENT '开始时间',
  `end` VARCHAR(45) NULL COMMENT '结束时间',
  `city` VARCHAR(45) NULL COMMENT '城市',
  `type` VARCHAR(45) NULL COMMENT '活动类型',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmq-community`.`articles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmq-community`.`articles` (
  `name` VARCHAR(45) NULL ,
  `date` VARCHAR(45) NULL,
  `abstract` VARCHAR(45) NULL,
  `thumbnail` VARCHAR(45) NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmq-community`.`authors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmq-community`.`authors` (
  `author_id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NULL,
  `image` VARCHAR(45) NULL,
  `exist` TINYINT NULL,
  `categories` VARCHAR(45) NULL,
  PRIMARY KEY (`author_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `rmq-community`.`tutorials`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `rmq-community`.`tutorials` (
  `id` INT NOT NULL AUTO_INCREMENT, 
  `cover` VARCHAR(45) NULL COMMENT '封面',
  `date` VARCHAR(45) NOT NULL,
  `download` VARCHAR(45) NULL COMMENT '下载地址',
  `name` VARCHAR(45) NULL COMMENT '名称',
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
